### ISSUE TITLE
no errors but no capture with Wallaby.js

### ISSUE THREAD

**Issue by yankeeinlondon** [jamesshore/test-console#3]
I have really benefitted from this library in the past and recently went to it on a Typescript/Node project I'm working on. The following code is about as basic as it gets:

    import { stdout, stderr } from 'test-console';
    const inspect = stdout.inspect();
    console.log('hello world');
    inspect.restore();
    // const output = stdout.inspectSync(f => console.log('hello world'));

    expect(inspect.output.length).to.equal(1);
    expect(inspect.output.indexOf('hello world')).to.not.equal(-1);

This test produces no errors but the test results both fail. Output is an empty array. Am I doing anything stupid?

**Comment by yankeeinlondon** [comment]
> Note: I tried the synchronous inspection as well (see commented code) but with the same results

**Comment by jamesshore** [comment]
The code looks correct. Perhaps run it through a debugger and see what's happening?

**Comment by jamesshore** [comment]
It's possible that something about your environment is preventing console.log from being redirected. (Line 19 of index.js.) Have you tried running the test-console tests in your environment? Alternatively, you could try editing index.js and instrumenting the code around line 19 to see what's going on.

**Comment by yankeeinlondon** [comment]
Yes this was the case. Wallaby redirects both **stdout** and **stderr** by default. As this is possibly a scenario other users may run into here's the solution for Wallaby testing:

In your `wallaby.js` configuration file add:

    setup:function () {
     if (!console._restored) {
       console.log = function () {
         console.log('restored');
         return require('console').Console.prototype.log.apply(this, arguments);
       }
       console.error = function () {
         return require('console').Console.prototype.error.apply(this, arguments);
       }
       console._restored = true;
     }
    },

The `setup()` function is run before each test and so therefore in the tests you want to observe these streams you must set `console._restored = true`. It will reset itself for the next test.

**Comment by jamesshore** [comment]
Thanks for tracking this down. Updated the title to make it easier for others to find.
