### ISSUE TITLE
Jest based testing log inclusion

### ISSUE THREAD

**Issue by Berkmann18** [jamesshore/test-console#7]
I just saw this package and integrated it to my Jest tests but oddly it seems to not give the same output as with the example on the README.

Here's the minimal test code:
```js
const stdout = require('test-console').stdout;

test('info', () => {
  const output = stdout.inspectSync(() => console.log('foo'));
  expect(outpu).toStrictEqual(['foo\n']);
})
```
The result is the following:
```bash
Expected value to equal:
      ["foo
    "]
    Received:
", "  console.log test/utils.test.js:7
        foo
    
    "]

    Difference:

    - Expected
    + Received

      Array [
    -   "foo
",
    +   "  console.log test/utils.test.js:7
    +     foo
    + 
      ",
      ]
```

So essentially it seems to not filter out something out.

I found that it was returning this:
```bash
 [ '\u001b[999D\u001b[K',
      '  \u001b[2mconsole.log\u001b[22m \u001b[2mtest/utils.test.js:7\u001b[22m\n    foo\n\n' ]
```
So it's not CLI colour agnostic and not targetted to what was printed via `inspectSync`.
Is this normal?

**Comment by jamesshore** [comment]
It looks like Jest is modifying console.log, and test-console is seeing those modifications. What happens if you output directly with `process.stdout.write()`?

**Comment by Berkmann18** [comment]
@jamesshore I tried using that which got this test to pass:
```js
test('info', () => {
  const output = stdout.inspectSync(() => process.stdout.write('foo'));
  expect(output).toStrictEqual(['foo']);
})
```
It also works fine with `'foo\n'` which (from what I read) is what `console.log` does under the hood.

**Comment by jamesshore** [comment]
Glad to hear it. Looks like the issue is that Jest modifies console.log.
